import React, { useState, useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';
import { 
  Layers, Plus, Search, X, Share2, Download, Code2, 
  Server, Database, Cloud, Box, Layout, FileText, Check, Copy,
  ChevronDown, FileImage, FileType, Image as ImageIcon
} from 'lucide-react';
import { getTools, getToolsByIds } from '../services/dataService';
import { Tool } from '../types';

interface StackLayer {
  id: string;
  name: string;
  icon: any;
  description: string;
  tools: Tool[];
}

export const StackBuilder: React.FC = () => {
  const [layers, setLayers] = useState<StackLayer[]>([
    { id: 'frontend', name: 'Frontend', icon: Layout, description: 'UI Libraries, Frameworks', tools: [] },
    { id: 'backend', name: 'Backend', icon: Server, description: 'Server Logic, API', tools: [] },
    { id: 'data', name: 'Data', icon: Database, description: 'Databases, ORMs', tools: [] },
    { id: 'infra', name: 'Infrastructure', icon: Cloud, description: 'Hosting, DevOps, CI/CD', tools: [] },
    { id: 'utilities', name: 'Utilities', icon: Box, description: 'Auth, Payments, Analytics', tools: [] },
  ]);

  const [activeLayerId, setActiveLayerId] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [showMarkdown, setShowMarkdown] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [copied, setCopied] = useState(false);
  const exportRef = useRef<HTMLDivElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const location = useLocation();

  const allTools = getTools();
  const filteredTools = search 
    ? allTools.filter(t => t.name.toLowerCase().includes(search.toLowerCase()) || t.category.toLowerCase().includes(search.toLowerCase()))
    : allTools.slice(0, 20);

  // Load stack from URL on mount
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const stackParam = params.get('stack');
    if (stackParam) {
      const toolIds = stackParam.split(',');
      const tools = getToolsByIds(toolIds);
      
      const newLayers = [...layers];
      tools.forEach(tool => {
        let layerId = 'utilities';
        const cat = tool.category.toLowerCase();
        const grp = tool.group.toLowerCase();
        
        if (cat.includes('frontend') || cat.includes('css') || cat.includes('ui')) layerId = 'frontend';
        else if (cat.includes('backend') || cat.includes('api')) layerId = 'backend';
        else if (cat.includes('data') || cat.includes('orm')) layerId = 'data';
        else if (grp.includes('hosting') || cat.includes('devops')) layerId = 'infra';
        
        const layer = newLayers.find(l => l.id === layerId);
        if (layer && !layer.tools.find(t => t.id === tool.id)) {
          layer.tools.push(tool);
        }
      });
      setLayers(newLayers);
    }
  }, []);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setShowExportMenu(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const addTool = (tool: Tool) => {
    if (activeLayerId) {
      setLayers(layers.map(l => 
        l.id === activeLayerId 
          ? { ...l, tools: [...l.tools, tool] } 
          : l
      ));
      setActiveLayerId(null);
      setSearch('');
    }
  };

  const removeTool = (layerId: string, toolId: string) => {
    setLayers(layers.map(l => 
      l.id === layerId 
        ? { ...l, tools: l.tools.filter(t => t.id !== toolId) } 
        : l
    ));
  };

  const applyTemplate = (type: 'MERN' | 'T3' | 'Enterprise') => {
    const baseLayers = layers.map(l => ({ ...l, tools: [] }));
    const find = (name: string) => allTools.find(t => t.name.toLowerCase().includes(name.toLowerCase()));

    if (type === 'MERN') {
      const react = find('React');
      const express = find('Express');
      const mongo = find('MongoDB') || allTools.find(t => t.category.includes('Database'));
      if (react) baseLayers[0].tools.push(react);
      if (express) baseLayers[1].tools.push(express);
      if (mongo) baseLayers[2].tools.push(mongo);
    } else if (type === 'T3') {
      const next = find('Next.js');
      const prisma = find('Prisma') || allTools.find(t => t.name.includes('ORM'));
      if (next) baseLayers[0].tools.push(next);
      if (prisma) baseLayers[2].tools.push(prisma);
    }

    setLayers(baseLayers);
  };

  const generateMarkdown = () => {
    let md = `# My Tech Stack\n\nGenerated by DevDirectory.net\n\n`;
    layers.forEach(layer => {
      if (layer.tools.length > 0) {
        md += `### ${layer.name}\n`;
        layer.tools.forEach(t => {
          md += `- [${t.name}](${t.websiteUrl}) - ${t.shortDescription}\n`;
        });
        md += '\n';
      }
    });
    return md;
  };

  const handleShare = () => {
    const allToolIds = layers.flatMap(l => l.tools.map(t => t.id));
    const url = `${window.location.origin}${window.location.pathname}?stack=${allToolIds.join(',')}`;
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = async (type: 'png' | 'jpg' | 'pdf' | 'md') => {
    setShowExportMenu(false);
    if (type === 'md') {
      setShowMarkdown(true);
      return;
    }

    if (!exportRef.current || !(window as any).html2canvas) {
      alert('Export feature requires libraries to be loaded. Please refresh the page.');
      return;
    }

    try {
      // Temporarily expand to full width for capture if needed, or rely on cloned document
      const canvas = await (window as any).html2canvas(exportRef.current, {
        scale: 3, // High resolution
        useCORS: true,
        allowTaint: true,
        backgroundColor: document.documentElement.classList.contains('dark') ? '#0f172a' : '#ffffff',
        windowWidth: 1600, // Force desktop layout capture
        onclone: (clonedDoc: Document) => {
            const container = clonedDoc.getElementById('export-container');
            if (container) {
              // Force styling for a clean, consistent export
              container.style.width = '1200px'; 
              container.style.maxWidth = 'none';
              container.style.padding = '40px';
              container.style.margin = '0 auto';
              
              // Hide interaction buttons
              const buttons = container.querySelectorAll('button');
              buttons.forEach((b: any) => b.style.display = 'none');
            }
        }
      });

      if (type === 'pdf') {
        const { jsPDF } = (window as any).jspdf;
        // Auto-detect orientation based on image dimensions
        const orientation = canvas.width > canvas.height ? 'l' : 'p';
        const pdf = new jsPDF(orientation, 'mm', 'a4');
        const imgData = canvas.toDataURL('image/png');
        
        const imgProps = pdf.getImageProperties(imgData);
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();
        
        // Calculate dimensions to fit keeping aspect ratio
        const ratio = imgProps.width / imgProps.height;
        let w = pdfWidth;
        let h = w / ratio;
        
        // If height exceeds page, fit by height
        if (h > pdfHeight) {
            h = pdfHeight;
            w = h * ratio;
        }

        // Center vertically and horizontally
        const x = (pdfWidth - w) / 2;
        const y = (pdfHeight - h) / 2;

        pdf.addImage(imgData, 'PNG', x, y, w, h);
        pdf.save('dev-stack.pdf');
      } else {
        const link = document.createElement('a');
        link.download = `dev-stack.${type === 'jpg' ? 'jpeg' : 'png'}`;
        link.href = canvas.toDataURL(`image/${type === 'jpg' ? 'jpeg' : 'png'}`);
        link.click();
      }
    } catch (err) {
      console.error('Export failed', err);
      alert('Failed to export. Please try again.');
    }
  };

  return (
    <div className="container mx-auto px-6 py-12">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-12 gap-6">
        <div>
          <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-4">System Architecture Designer</h1>
          <p className="text-slate-600 dark:text-slate-400 max-w-2xl">
            Drag, drop, and design your complete end-to-end stack. Export to GitHub README when done.
          </p>
        </div>
        <div className="flex gap-3">
          <button onClick={handleShare} className="flex items-center gap-2 px-4 py-2 bg-slate-100 dark:bg-white/5 text-slate-700 dark:text-slate-300 rounded-lg font-bold hover:bg-slate-200 dark:hover:bg-white/10 transition-colors">
            {copied ? <Check className="w-4 h-4 text-green-500" /> : <Share2 className="w-4 h-4" />}
            {copied ? 'Copied Link' : 'Share'}
          </button>
          
          <div className="relative" ref={dropdownRef}>
            <button 
              onClick={() => setShowExportMenu(!showExportMenu)}
              className="flex items-center gap-2 px-4 py-2 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-lg font-bold hover:opacity-90 transition-opacity"
            >
              <Download className="w-4 h-4" /> Export <ChevronDown className="w-4 h-4" />
            </button>
            
            {showExportMenu && (
              <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-navy-800 rounded-xl shadow-xl border border-slate-200 dark:border-white/10 z-50 overflow-hidden animate-fade-in">
                <button onClick={() => handleExport('png')} className="w-full text-left px-4 py-3 hover:bg-slate-50 dark:hover:bg-white/5 flex items-center gap-3 text-slate-700 dark:text-slate-300">
                  <FileImage className="w-4 h-4" /> Export as PNG
                </button>
                <button onClick={() => handleExport('jpg')} className="w-full text-left px-4 py-3 hover:bg-slate-50 dark:hover:bg-white/5 flex items-center gap-3 text-slate-700 dark:text-slate-300">
                  <ImageIcon className="w-4 h-4" /> Export as JPG
                </button>
                <button onClick={() => handleExport('pdf')} className="w-full text-left px-4 py-3 hover:bg-slate-50 dark:hover:bg-white/5 flex items-center gap-3 text-slate-700 dark:text-slate-300">
                  <FileType className="w-4 h-4" /> Export as PDF
                </button>
                <div className="h-px bg-slate-100 dark:bg-white/5 my-1"></div>
                <button onClick={() => handleExport('md')} className="w-full text-left px-4 py-3 hover:bg-slate-50 dark:hover:bg-white/5 flex items-center gap-3 text-slate-700 dark:text-slate-300">
                  <FileText className="w-4 h-4" /> Copy Markdown
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Templates */}
      <div className="mb-12">
        <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-4">Quick Start Templates</h3>
        <div className="flex flex-wrap gap-4">
          <button onClick={() => applyTemplate('MERN')} className="px-4 py-2 border border-slate-200 dark:border-white/10 rounded-full text-sm font-medium hover:border-teal-500 hover:text-teal-600 dark:hover:text-teal-400 transition-colors">
            ⚛️ MERN Stack
          </button>
          <button onClick={() => applyTemplate('T3')} className="px-4 py-2 border border-slate-200 dark:border-white/10 rounded-full text-sm font-medium hover:border-teal-500 hover:text-teal-600 dark:hover:text-teal-400 transition-colors">
            🚀 T3 Stack
          </button>
        </div>
      </div>

      {/* Layers Board (Export Area) */}
      <div ref={exportRef} id="export-container" className="bg-white dark:bg-navy-950 p-1 rounded-xl">
        <div className="space-y-6">
          {layers.map((layer) => (
            <div key={layer.id} className="bg-white dark:bg-navy-800 border border-slate-200 dark:border-white/5 rounded-xl overflow-hidden shadow-sm">
              <div className="bg-slate-50 dark:bg-navy-900/50 px-6 py-4 border-b border-slate-200 dark:border-white/5 flex justify-between items-center">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-white dark:bg-navy-800 rounded-lg shadow-sm text-teal-600 dark:text-teal-400">
                    <layer.icon className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="font-bold text-slate-900 dark:text-white">{layer.name}</h3>
                    <p className="text-xs text-slate-500 dark:text-slate-400 hidden sm:block">{layer.description}</p>
                  </div>
                </div>
                <button 
                  onClick={() => setActiveLayerId(layer.id)}
                  className="flex items-center gap-1 text-xs font-bold bg-teal-500 text-white px-3 py-1.5 rounded-lg hover:bg-teal-600 transition-colors"
                >
                  <Plus className="w-3 h-3" /> Add Tool
                </button>
              </div>
              
              <div className="p-6 min-h-[120px] bg-slate-50/50 dark:bg-navy-900/20">
                {layer.tools.length > 0 ? (
                  <div className="flex flex-wrap gap-4">
                    {layer.tools.map(tool => (
                      <div key={tool.id} className="group relative flex items-center gap-3 bg-white dark:bg-navy-800 border border-slate-200 dark:border-white/10 rounded-xl p-3 pr-8 shadow-sm hover:shadow-md transition-all">
                        <img src={tool.logo} alt={tool.name} className="w-10 h-10 rounded-lg bg-slate-100 dark:bg-navy-950 object-cover" />
                        <div>
                          <div className="font-bold text-sm text-slate-900 dark:text-white">{tool.name}</div>
                          <div className="text-[10px] text-slate-500">{tool.category}</div>
                        </div>
                        <button 
                          onClick={() => removeTool(layer.id, tool.id)}
                          className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 text-slate-400 hover:text-red-500 transition-all"
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center h-full py-4 text-slate-400 border-2 border-dashed border-slate-200 dark:border-white/5 rounded-lg">
                    <span className="text-sm">No tools selected</span>
                    <button onClick={() => setActiveLayerId(layer.id)} className="text-teal-500 text-xs mt-1 hover:underline">Add one</button>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
        
        {/* Export Footer */}
        <div id="stack-export-footer" className="mt-8 pt-4 border-t border-slate-100 dark:border-white/5 flex items-center justify-between text-slate-400 dark:text-slate-500">
           <div className="flex items-center gap-2">
             <div className="w-6 h-6 rounded bg-teal-500 flex items-center justify-center text-white font-bold text-xs">D</div>
             <span className="font-bold text-sm tracking-tight text-slate-700 dark:text-slate-300">
              Powered by <span className="text-teal-600 dark:text-teal-400">DevDirectory.net</span>
             </span>
           </div>
           <span className="text-xs">Generated on {new Date().toLocaleDateString()}</span>
        </div>
      </div>

      {/* Tool Selector Modal */}
      {activeLayerId && (
        <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 animate-fade-in">
          <div className="bg-white dark:bg-navy-800 w-full max-w-lg rounded-2xl shadow-2xl overflow-hidden animate-slide-up flex flex-col max-h-[80vh]">
            <div className="p-4 border-b border-slate-200 dark:border-white/10 flex items-center gap-3 shrink-0">
              <Search className="w-5 h-5 text-slate-400" />
              <input 
                autoFocus
                placeholder="Search tools..." 
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="flex-1 bg-transparent outline-none text-slate-900 dark:text-white placeholder:text-slate-400"
              />
              <button onClick={() => setActiveLayerId(null)}><X className="w-5 h-5 text-slate-400 hover:text-slate-600" /></button>
            </div>
            <div className="overflow-y-auto p-2 flex-1">
              {filteredTools.map(tool => (
                <button
                  key={tool.id}
                  onClick={() => addTool(tool)}
                  className="w-full flex items-center gap-4 p-3 hover:bg-slate-50 dark:hover:bg-white/5 rounded-xl transition-colors text-left group"
                >
                  <img src={tool.logo} className="w-10 h-10 rounded-lg bg-slate-100 border border-slate-200 dark:border-white/10 object-cover" />
                  <div>
                    <div className="font-bold text-slate-900 dark:text-white group-hover:text-teal-600 dark:group-hover:text-teal-400 transition-colors">{tool.name}</div>
                    <div className="text-xs text-slate-500">{tool.category}</div>
                  </div>
                  <Plus className="w-4 h-4 ml-auto text-slate-300 group-hover:text-teal-500" />
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Markdown Modal */}
      {showMarkdown && (
        <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 animate-fade-in">
          <div className="bg-white dark:bg-navy-800 w-full max-w-2xl rounded-2xl shadow-2xl overflow-hidden animate-slide-up flex flex-col max-h-[80vh]">
            <div className="p-4 border-b border-slate-200 dark:border-white/10 flex justify-between items-center">
              <h3 className="font-bold text-lg text-slate-900 dark:text-white">Export to Markdown</h3>
              <button onClick={() => setShowMarkdown(false)}><X className="w-5 h-5 text-slate-400" /></button>
            </div>
            <div className="p-6 overflow-y-auto bg-slate-50 dark:bg-navy-950 flex-1">
              <pre className="text-sm font-mono text-slate-700 dark:text-slate-300 whitespace-pre-wrap">{generateMarkdown()}</pre>
            </div>
            <div className="p-4 border-t border-slate-200 dark:border-white/10 flex justify-end">
              <button 
                onClick={() => { navigator.clipboard.writeText(generateMarkdown()); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
                className="bg-teal-500 text-white px-6 py-2 rounded-lg font-bold hover:bg-teal-600 transition-colors flex items-center gap-2"
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy to Clipboard'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};